USE PERSONS_DATABASE;

DROP TABLE IF EXISTS PERSONS;
DROP TABLE IF EXISTS TEACHER;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS COLLEGE_STUDENT;

CREATE TABLE IF NOT EXISTS PERSONS(
	PERSONS_ID serial;
    NAME VARCHAR(30) NOT NULL;
    AGE INT NOT NULL;
	GENDER VARCHAR(1) NOT NULL
    );
CREATE TABLE IF NOT EXISTS TEACHER(
TEACHER_ID serial;
SALARY INT NOT NULL;
SUBJECT VARCHAR(45) NOT NULL
);
CREATE TABLE IF NOT EXISTS STUDENT(
	STUDENT_ID SERIAL;
    ID_NUMBER INT NOT NULL;
    GPA DOUBLE NOT NULL DEFAULT 0.0

);
CREATE TABLE IF NOT EXISTS COLLEGE_STUDENT(
 COLLEGE_STUDENT_ID SERIAL;
 YEAR INT NOT NULL;
 MAJOR VARCHAR(45)
 );